services:
  - type: web
    name: sistema-educativo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sistema_educativo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railway
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4